var annotated_dup =
[
    [ "BuyItemHandler", "class_buy_item_handler.html", "class_buy_item_handler" ],
    [ "CashDisplay", "class_cash_display.html", "class_cash_display" ],
    [ "Customer", "class_customer.html", "class_customer" ],
    [ "CustomerSpawner", "class_customer_spawner.html", "class_customer_spawner" ],
    [ "DailyStats", "struct_daily_stats.html", "struct_daily_stats" ],
    [ "DailySummaryManager", "class_daily_summary_manager.html", "class_daily_summary_manager" ],
    [ "DayCycle", "class_day_cycle.html", "class_day_cycle" ],
    [ "DynamicContentSizeForOneColumn", "class_dynamic_content_size_for_one_column.html", "class_dynamic_content_size_for_one_column" ],
    [ "DynamicContentSizeForTwoColumns", "class_dynamic_content_size_for_two_columns.html", "class_dynamic_content_size_for_two_columns" ],
    [ "InformationBar", "class_information_bar.html", "class_information_bar" ],
    [ "InventoryItem", "class_inventory_item.html", "class_inventory_item" ],
    [ "InventoryItemUI", "class_inventory_item_u_i.html", "class_inventory_item_u_i" ],
    [ "InventoryManager", "class_inventory_manager.html", "class_inventory_manager" ],
    [ "NavigationController", "class_navigation_controller.html", "class_navigation_controller" ],
    [ "OverallSummaryManager", "class_overall_summary_manager.html", "class_overall_summary_manager" ],
    [ "ReceiptGenerator", "class_receipt_generator.html", "class_receipt_generator" ],
    [ "ShelfItemUI", "class_shelf_item_u_i.html", "class_shelf_item_u_i" ],
    [ "ShelfManager", "class_shelf_manager.html", "class_shelf_manager" ],
    [ "ShopFloorManager", "class_shop_floor_manager.html", "class_shop_floor_manager" ],
    [ "StartAtTop", "class_start_at_top.html", "class_start_at_top" ],
    [ "SummaryPrefabScript", "class_summary_prefab_script.html", "class_summary_prefab_script" ],
    [ "TillManager", "class_till_manager.html", "class_till_manager" ],
    [ "WholesaleItemUI", "class_wholesale_item_u_i.html", "class_wholesale_item_u_i" ],
    [ "WholesaleManager", "class_wholesale_manager.html", "class_wholesale_manager" ]
];